### ISSUE TITLE
Make presentation slides PDF available? 

### ISSUE THREAD

**Issue by vincent-peng** [AnthonyEgerton/time-travel-testing#1]
Hi Anthony,

Thanks for the great storytelling presentation last night at CocoaHeads. Is there any chance that you would make the presentation slides available?

Regards,
Vincent

**Comment by AnthonyEgerton** [comment]
I'm going to put up a video of the presentation, would that be sufficient?
Or would you like the slides as a pdf as well?

**Comment by vincent-peng** [comment]
I think the video surely would be sufficient and appreciate.
Cheers.

**Comment by AnthonyEgerton** [comment]
Updated readme with link to video.
[Watch Video](https://vimeo.com/146536576)
